### ISSUE TITLE
API rate plan change feature NOT available for an existing user

### ISSUE THREAD

**Issue by Hmittal15** [BigDataIA-Spring2023-Team-11/Assignment3#10]
**Expected Behavior**
Existing user should be able to update their existing API rateplan.

**Current Behavior**
API rate plan change feature is not available for an existing user.
![image](https://user-images.githubusercontent.com/108916132/225506035-ee129c5c-4739-4bee-b6de-4c5b76e46d91.png)

**Possible Solution**
Design a UI to give user an option to update their API rate plan. Develop a function to update the current plan with user provided new plan.

**Steps to Reproduce**
1. Login with an existing user.
2. Browse the complete web application, unable to find the option to update API rate plan.

**Possible Implementation**
Design an API to first validate the existing user and fetch their current rateplan. Design front-end interface for user to provide them with an option to update their existing plan. Fetch the updated plan from UI and update the same inuser DB. Moving forward this updated plan should be utilized for tapping the user's API usage.

**Comment by abhatt13** [comment]
As it is not mentioned as a requirement we did not incorporate this feature into our application. However, we can leverage it into our further application development plans.
