### ISSUE TITLE
User API requests not getting logged

### ISSUE THREAD

**Issue by Hmittal15** [BigDataIA-Spring2023-Team-11/Assignment3#12]
**Expected Behavior**
Each API request maid by the user should get logged and deducted from their plan quota.

**Current Behavior**
API requests are not getting logged. User is able to make API calls even post their quota limit, and call count is not getting updated. Also, the dashboard is not getting updated and shows 0 call count for the user even after making calls.
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/108916132/225510113-48e0ac7f-f4f9-41f2-979e-abd324facecb.png">

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/108916132/225510166-c11ad57c-c148-4377-a00c-f03b3d238a7a.png">

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/108916132/225510208-5ca90ceb-ad13-49a1-ac7c-9a5beaeac12b.png">

**Possible Solution**
Maintain a API call count DB or logs and monitor each call made by the user. If the number of calls exceeds past their rateplan, then they should be prompted accordingly, and prevented from making further requests.

**Steps to Reproduce**
1. Login with an existing user.
2. Verify their rateplan.
3. Navigate to NEXRAD/Goes18 page and try to make some API calls by downloading files.
4. If the user has a 'Free' tier rateplan, try to make more than 10 calls.
5. Navigate to 'Dashboard' page and verify the result.

**Possible Implementation**
Create a DB which logs all the user actions. Maintain a count of all the API endpoints that a user triggers. Fetch the user's existing rateplan from user DB. Constantly check this maximum permissible limit with the actual call requests which user has made. If the user exceeds their rateplan limit, give them a corresponding prompt and prevent them from making further calls.

**Comment by abhatt13** [comment]
We have implemented API rate limit only on the GETURL(BUTTON) API endpoint. The reason for not limiting the dropdown of files is we don't want the user to waste their API calls on just accidently selecting the wrong files.
